# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true
    brochures_directory: '%kernel.project_dir%/public/uploads/brochures'
    purchases_files_directory: '%kernel.project_dir%/public/uploads/purchasesFiles'
    article_title_img_directory: '%kernel.project_dir%/public/uploads/articleTitles'
    article_files_directory: '%kernel.project_dir%/public/uploads/articleFiles'
    infrastructure_sheet_files_directory: '%kernel.project_dir%/public/uploads/infrastructureSheetsFiles'
    documents_files_directory: '%kernel.project_dir%/public/uploads/documentsFiles'
    employees_photos_directory: '%kernel.project_dir%/public/uploads/employeesPhotos'
    design_project_example_directory: '%kernel.project_dir%/public/uploads/designProjectExample'
    design_project_example_directory_presentation: '%kernel.project_dir%/public/uploads/designProjectExamplePresentation'
    partners_logo_directory: '%kernel.project_dir%/public/uploads/partnersLogo'
    infrastructure_sheet_region_directory: '%kernel.project_dir%/public/uploads/infrastructureSheetsRegion'
    closing_files_directory: '%kernel.project_dir%/public/uploads/closingFiles'
    payment_orders_directory: '%kernel.project_dir%/public/uploads/paymentOrders'
    additional_agreement_directory: '%kernel.project_dir%/public/uploads/additionalAgreement'
    contracting_tables_directory: '%kernel.project_dir%/public/uploads/contractingTables'
    repair_photos_directory: '%kernel.project_dir%/public/uploads/repairPhotos'
    cluster_documents_directory: '%kernel.project_dir%/public/uploads/clusterDocuments'
    another_documents_directory: '%kernel.project_dir%/public/uploads/anotherDocument'
    readiness_map_archive_directory: '%kernel.project_dir%/public/uploads/readinessMapArchive'
    readiness_map_template_file: '%kernel.project_dir%/public/word/Карта готовности Кластеры.docx'
    contrating_template_file: '%kernel.project_dir%/public/excel/contracting.xlsx'
    excel_files_directory: '%kernel.project_dir%/public/excel/'
    readiness_map_table_template_file: '%kernel.project_dir%/public/excel/readinessMap.xlsx'
    readiness_map_table_bas_template_file: '%kernel.project_dir%/public/excel/Шаблон_Карта_готовности бас.xlsx'
    readiness_map_table_template_file_new: '%kernel.project_dir%/public/excel/Шаблон ремработ и оборудования.xlsx'
    cluster_photo_directory: '%kernel.project_dir%/public/uploads/clusterPhoto'
    readiness_map_saves_directory: '%kernel.project_dir%/public/uploads/readinessMapSaves'
    zones_design_project_directory: '%kernel.project_dir%/public/uploads/zonesDesignProject'
    test_upload_directory: '%kernel.project_dir%/public/uploads/testUploadDirectory'
    cluster_request_table_directory: '%kernel.project_dir%/public/uploads/clusterRequestTable'
    cluster_request_certificate: '%kernel.project_dir%/public/word/справка по заявкам.docx'
    pdf_files_directory: '%kernel.project_dir%/public/pdf/'
    certificate_files_directory: '%kernel.project_dir%/public/uploads/certificate/'
    event_files_directory: '%kernel.project_dir%/public/uploads/eventFiles/'
    purchases_table_directory: '%kernel.project_dir%/public/uploads/purchasesTable/'
    monitoring_check_out_directory: '%kernel.project_dir%/public/uploads/monitoringCheckOut/'
    procurement_procedures_table_directory: '%kernel.project_dir%/public/excel/ProcurementProceduresTable_v2.xlsx'
    procurement_procedures_table_bas_directory: '%kernel.project_dir%/public/excel/Закупочные процедуры ШАБЛОН бас.xlsx'
    typical_table_bas_directory: '%kernel.project_dir%/public/excel/typical.xlsx'
    compitence_profile_directory: '%kernel.project_dir%/public/uploads/compitenceProfile/'
    compitence_profile_template_directory: '%kernel.project_dir%/public/word/Шаблон_для_заполнения_Профиль_компетенций_выпускника.docx'


services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\DatabaseOnFlushListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
#    App\Twig\AppExtension:
#        lazy: true
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
            arguments:
                - '%env(DATABASE_URL)%'
                - { db_table: 'new_session', db_id_col: 'sess_id' }